config/routes.rb
Thefirehose::Application.routes.draw do
  resources :links
  get "/links/tagged/:id", to: "links#index"
  get "/links/user/:id", to: "links#index"
  get "/readings", to: "readings#index"
  post "/readings", to: "readings#create"
  root to: "static_pages#index"
  get '/login', :to => 'sessions#new', :as => :login
  get '/auth/github/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get '/logout', to: 'sessions#destroy'
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  validates :uid, :provider, :user_id, presence: true

  def self.find_or_create(auth_hash)
    unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      user = User.create name: auth_hash["info"]["nickname"], email: auth_hash["info"]["email"], provider: auth_hash["provider"], gravatar: auth_hash["extra"]["raw_info"]["avatar_url"]
      auth = create :user => user, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end

    auth
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  acts_as_taggable_on :tags
  belongs_to :user
  validates :title, presence: true
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true


  def printable_url
    if /(https:\/\/)/.match(self.url) != nil
      self.url
    elsif /(http:\/\/)/.match(self.url) != nil
      self.url
    else
      "http://#{self.url}"
    end
  end

  def tag_links
    self.tag_list_on(:tags).each do |tag|
      return "<a href='links/tagged/#{tag}'>#{tag}</a>"
    end
  end

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :link
  belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  has_many :links
  has_many :readings

  validates :email, :provider, presence: true
  validates :name, presence: true, uniqueness: true

  def add_provider(auth_hash)
    # Check if the provider already exists, so we don't add it twice
    unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    current_user = User.find(session[:user_id]) if session[:user_id].present?
  end

  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  
  
  # GET /links
  # GET /links.json
  def index
    if params[:user].present?
      @links = Link.where(user_id: params[:user]).reverse
      @user = User.find(@links.first.user.id)
    elsif params[:tag].present?
      @links = Link.tagged_with(params[:tag]).reverse
    else
      @links = Link.all.reverse
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    @link.user_id = session[:user_id]

    respond_to do |format|
      if @link.save
        format.html { redirect_to links_url, notice: 'Thanks for submitting your link!' }
        format.json { render action: 'show', status: :created, location: @link }
      else
        format.html { render action: 'new' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:url, :description, :tag_list, :title)
    end

  def check_login
    if !session[:user_id]
      redirect_to root_url
    end
  end
end

app/controllers/readings_controller.rb
class  ReadingsController < ApplicationController
  def index
    @readings = Reading.all.where(user_id: current_user.id)
  end

  def create
    Reading.create(user_id: params[:user_id], title: params[:title], url: params[:url], description: params[:description], is_active: true)
    redirect_to "/readings"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth_hash = request.env['omniauth.auth']

    if session[:user_id]
      # Means our user is signed in. Add the authorization to the user
      User.find(session[:user_id]).add_provider(auth_hash)

      render :text => "You can now login using #{auth_hash["provider"].capitalize} too!"
    else
      # Log him in or sign him up
      auth = Authorization.find_or_create(auth_hash)

      # Create the session
      session[:user_id] = auth.user.id
      redirect_to root_url, notice: "Welcome #{User.find(session[:user_id]).name}!"
      #render :text => auth_hash
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You've Logged Out!"
  end

  def failure
    render :text => "Sorry, but you didn't allow access to our app!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    if current_user
      redirect_to links_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thefirehose</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">


    <% if flash[:notice].present? %>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p><%= flash[:notice] %></p>
      </div>

    <% end %>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">The Firehose</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tags <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% tag_cloud Link.tag_counts, %w{s m l} do |tag| %>
                  <li><%= link_to tag.name, "/links?tag=#{tag.name}" %></li>
                <% end %>
              </ul>
            </li>
          </ul>
          <% if current_user %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Add New Link", new_link_path, class: "add_new_link btn-primary" %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle user_drop" data-toggle="dropdown"><img src="<%= current_user.gravatar %>" class="avatar" alt="<%= current_user.name %>"/><%= current_user.name %>
                  <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="/links?user=<%= current_user.id %>">My Links</a></li>
                  <li><a href="/readings">My Reading List</a></li>
                  <li class="divider"></li>
                  <li><a href="/logout">Logout</a></li>
                </ul>
              </li>
            </ul>
          <% end %>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </div>
  <div class="col-md-2">

  </div>

</div>


</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link, :html => { :class => "form-horizontal", role: "form" } ) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation" class="alert-danger">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of Link", maxlength: 255 %>
  </div>
  <div class="form-group">
    <%= f.text_field :url, class: "form-control", placeholder: "Link URL (http://google.com)" %>
  </div>
  <div class="form-group">
    <%= f.text_field :description, class: "form-control", placeholder: "Brief Description of Link" %>
  </div>
  <div class="form-group">
    <%= f.text_field :tag_list, class: "form-control", placeholder: "Tags (separate by comma)" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Link", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<div class="row">

  <div class="col-md-4">

  </div>

  <div class="col-md-4">
    <div class="well well-lg">
      <h1 class="text-align-center">Edit Link</h1>
      <%= render 'form' %>
    </div>
  </div>

  <div class="col-md-4">

  </div>

</div>

app/views/links/index.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <% if @user %>
      <div class="well well-sm">
        <img src="<%= @user.gravatar %>" alt="<%= @user.name %>" class="avatar-lg"><h3>Submitted by <%= @user.name %></h3>
      </div>
    <% end %>
    <div class="row">
      <% @links.each do |link| %>
        <div class="panel panel-default">
          <div class="panel-heading link-heading">
            <a href="<%= link.printable_url %>" class="panel-title col-md-7" target="_blank"><%= link.title %></a>
            <div class="tag_list col-md-5">
              <% link.tag_list_on(:tags).each do |tag| %>
                <a href="/links?tag=<%= tag %>"><%= tag %></a>
              <% end %>
            </div>

          </div>
          <div class="panel-body">
            <p class="list-group-item-text col-md-10"><%= link.description %></p>
            <div class="link_meta col-md-2">
              <div class="btn-group">
                <button type="button" onClick="parent.location='/links?user=<%= link.user.id %>'"class="btn btn-primary btn-sm link_user_info tip" data-original-title="Posted by <%= link.user.name %>">
                  <span class="glyphicon glyphicon-user tip"></span>
                </button>
                <button type="button submit" form="add_reading<%= link.id %>" class="btn btn-info btn-sm add_reading tip" data-original-title="Add link to reading list">
                  <span class="glyphicon glyphicon-share"></span>
                </button>
              </div>
              <form action="/readings" method="post" id="add_reading<%= link.id %>">
                <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
                <input type="hidden" name="title" value="<%= link.title %>">
                <input type="hidden" name="description" value="<%= link.description %>">
                <input type="hidden" name="url" value="<%= link.printable_url%>">
                <input type="hidden" name="user_id" value="<%= current_user.id %>">
              </form>

            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/links/new.html.erb
<div class="row">

  <div class="col-md-2">

  </div>

  <div class="col-md-8">
    <div class="progress progress-striped">
      <div class="progress-bar progress-bar-info"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" >
      </div>
    </div>
    <div class="well well-lg">
      <h1 class="text-align-center">Add New link</h1>
      <%= render 'form' %>
      <div id="tag_cloud">
        <p>Popular tags:</p>
        <% tag_cloud Link.tag_counts, %w{s m l} do |tag, css_class| %>
          <%= link_to tag.name, "/links?=tag#{tag.name}", class: css_class %>
        <% end %>
      </div>
     </div>
  </div>

  <div class="col-md-2">

  </div>

</div>

app/views/links/show.html.erb
<div class="row">
<div class="col-md-3">

</div>
<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><a href="<%= @link.printable_url %>" target="blank"><%= @link.title %></a></h3>
    </div>
    <div class="panel-body">
      <%= @link.description %>
    </div>
  </div>
</div>
<div class="col-md-3">

</div>



</div>
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/readings/index.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="row">
      <% @readings.each do |reading| %>
        <div class="panel panel-default">
          <div class="panel-heading link-heading">
            <a href="<%= reading.url %>" class="panel-title col-md-7" target="_blank"><%= reading.title %></a>
          </div>
          <div class="panel-body">
            <p class="list-group-item-text col-md-8"><%= reading.description %></p>
            <div class="link_meta col-md-4">
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1>The Firehose</h1>
  <p>A place for gSchool students to share links to useful information</p>
  <p><%= link_to "Login with Github", "/auth/github/", class: "btn btn-primary", role: "button" %>
  </p>
</div>
<%= current_user.name if current_user %>